image: 'maven:3.8.4-openjdk-17-slim'

cache:
  paths:
    - .m2/repository

variables:
  PROJECT_ARTIFACT_ID: kypo-rest-training
  DEPLOYMENT_INFO_VERSION_FILE: VERSION.txt
  MAVEN_CLI_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  TRUSTED_HOST: gitlab.ics.muni.cz
  GIT_CLONE_URL: "git@${CI_SERVER_HOST}:${CI_PROJECT_PATH}.git"

stages:
  - docker_image_push_development


docker_image_push_development:
  before_script: [] #prevent global before_script from running
  variables:
    CI_CUSTOM_IMAGE_NAME: kypo-training-service
  stage: docker_image_push
  image:
    name: gcr.io/kaniko-project/executor:v1.3.0-debug
    entrypoint: [ "" ]
  script:
    - export CI_CUSTOM_REGISTRY_IMAGE="${CI_REGISTRY}/${CI_CUSTOM_REGISTRY_PATH}/${CI_CUSTOM_IMAGE_NAME}"
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_CUSTOM_REGISTRY_USER\",\"password\":\"$CI_CUSTOM_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_CUSTOM_REGISTRY_IMAGE:develop --build-arg PROPRIETARY_REPO_URL=$PROPRIETARY_REPO_URL


